name: links

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421 # v1.8.0
        with:
          # Check all markdown in /content/
          # Exclude twitter.com links because they always 503 unless logged in
          args: --verbose --no-progress --exclude twitter.com './content/'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
